#!/usr/bin/env python3
"""
Verticons Dock Generator
-------------------------
Reads games.json (the list of games/apps in your dock) and regenerates
Icons.ini with all positions, push-down cascades, and zone sizing
calculated automatically.

USAGE:
    1. Put this script, games.json, assets/, and Scripts/ all in the
       same folder (your Verticons\\Icons\\ skin folder).
    2. Edit games.json to add, remove, or reorder icons.
    3. Run:  python generate_dock.py
    4. In Rainmeter: right-click the skin -> Refresh Skin.

games.json format (a list of objects):
    {
        "id": "SectionName",          <- no spaces, must be unique
        "name": "Display Name",       <- shown as the hover label
        "image": "file.png",          <- must exist in assets/
        "shortcut": "C:\\...\\Game.lnk"
    }

The script will warn you if:
    - an entry in games.json points to a missing image file
    - an image file exists in assets/ but isn't in games.json yet
"""

import json
import os
import sys

# ---- Configuration ----
SKIN_DIR = os.path.dirname(os.path.abspath(__file__))
ASSETS_DIR = os.path.join(SKIN_DIR, "assets")
MANIFEST_PATH = os.path.join(SKIN_DIR, "games.json")
OUTPUT_PATH = os.path.join(SKIN_DIR, "Icons.ini")

UPDATE_MS = 33  # ~30fps - plenty smooth for icon-sized motion, half the idle overhead of 60fps
ICON_SIZE = 36
ICON_SIZE_HOVER = 70
GAP = 12
START_Y = 20
DOCK_X = 14
SLIDE_DISTANCE = 20
LABEL_GAP = 12
FONT_CLR = "255,255,255,255"
FONT_SIZE = 11
FONT_FACE = "Segoe UI"

PUSH_AMOUNT = ICON_SIZE_HOVER - ICON_SIZE


def load_manifest():
    if not os.path.exists(MANIFEST_PATH):
        sys.exit(f"ERROR: {MANIFEST_PATH} not found. Create it first (see games.json example).")
    with open(MANIFEST_PATH, "r", encoding="utf-8") as f:
        games = json.load(f)

    if not isinstance(games, list):
        sys.exit(
            "ERROR: games.json must be a [ ] list of entries at the top level, "
            f"but found a {type(games).__name__} instead. Wrap your entries "
            "in square brackets, e.g. [ {...}, {...} ]."
        )

    required = {"id", "name", "image", "shortcut"}
    seen_ids = set()
    for i, g in enumerate(games):
        if not isinstance(g, dict):
            sys.exit(
                f"ERROR: entry #{i + 1} in games.json is not a {{...}} object "
                f"(got: {g!r}). Check for a missing brace, bracket, or comma "
                f"near that entry."
            )
        missing = required - g.keys()
        if missing:
            sys.exit(f"ERROR: manifest entry {g} is missing fields: {missing}")
        if " " in g["id"]:
            sys.exit(f"ERROR: id '{g['id']}' cannot contain spaces.")
        if g["id"] in seen_ids:
            sys.exit(f"ERROR: duplicate id '{g['id']}' in games.json.")
        seen_ids.add(g["id"])
    return games


def check_assets(games):
    manifest_images = {g["image"] for g in games}
    actual_images = set()
    if os.path.isdir(ASSETS_DIR):
        actual_images = {f for f in os.listdir(ASSETS_DIR) if f.lower().endswith((".png", ".ico"))}
    else:
        print(f"⚠  assets/ folder not found at {ASSETS_DIR}")
        return

    missing_files = manifest_images - actual_images
    orphan_files = actual_images - manifest_images

    if missing_files:
        print("⚠  These games.json entries point to images that DON'T exist in assets/:")
        for m in sorted(missing_files):
            print(f"     - {m}")

    if orphan_files:
        print("⚠  These image files exist in assets/ but AREN'T in games.json yet:")
        for o in sorted(orphan_files):
            print(f"     - {o}   (add an entry to games.json to include it in the dock)")

    if not missing_files and not orphan_files:
        print("✓ assets/ and games.json are in sync.")


def rest_y(index):
    return START_Y + index * (ICON_SIZE + GAP)


def build_ini(games):
    n = len(games)
    lines = []

    lines += [
        "[Rainmeter]",
        f"Update={UPDATE_MS}",
        "AccurateText=1",
        "",
        "[Metadata]",
        "Name=Verticons",
        "Author=Muhammad Abdullah",
        "Information=Auto-hide magnetic dock - generated by generate_dock.py",
        "Version=3.0",
        "License=WTFPL",
        "",
        "[Variables]",
        f"IconSize={ICON_SIZE}",
        f"IconSizeHover={ICON_SIZE_HOVER}",
        f"DockX={DOCK_X}",
        f"SlideDistance={SLIDE_DISTANCE}",
        f"LabelGap={LABEL_GAP}",
        f"FontClr={FONT_CLR}",
        f"PushAmount={PUSH_AMOUNT}",
        "",
        "[FadeScript]",
        "Measure=Script",
        "ScriptFile=Scripts\\Fade.lua",
        "",
    ]

    # one independent growth tween per icon - each Script measure gets
    # its own isolated Lua state even though they all share Tween.lua
    for g in games:
        lines += [
            f'[Tween{g["id"]}]',
            "Measure=Script",
            "ScriptFile=Scripts\\Tween.lua",
            "",
        ]

    edge_h = rest_y(n - 1) + ICON_SIZE + 10
    hover_h = rest_y(n - 1) + PUSH_AMOUNT + ICON_SIZE_HOVER + 20
    longest_name = max((len(g["name"]) for g in games), default=10)
    hover_w = DOCK_X + ICON_SIZE_HOVER + LABEL_GAP + longest_name * 8 + 20

    lines += [
        "[EdgeSensor]",
        "Meter=Image",
        "SolidColor=0,0,0,1",
        "X=0",
        "Y=10",
        "W=12",
        f"H={edge_h}",
        'MouseOverAction=[!CommandMeasure FadeScript "Show()"]',
        "",
    ]

    # global reset bang used when the mouse leaves the whole dock:
    # collapse every tween back to 0 and re-greyscale everything
    reset_bangs = []
    for g in games:
        gid = g["id"]
        reset_bangs.append(f'[!CommandMeasure Tween{gid} "Hide()"]')
        reset_bangs.append(f'[!SetOption {gid} "Greyscale" "1"]')
    reset_bangs.append("[!HideMeterGroup Labels]")

    lines += [
        "[HoverZone]",
        "Meter=Image",
        "SolidColor=0,0,0,1",
        "X=0",
        "Y=0",
        f"W={hover_w}",
        f"H={hover_h}",
        'MouseOverAction=[!CommandMeasure FadeScript "Show()"]',
        'MouseLeaveAction=[!CommandMeasure FadeScript "Hide()"]' + "".join(reset_bangs),
        "",
    ]

    edge_bar_h = rest_y(n - 1) + ICON_SIZE - START_Y + 10
    lines += [
        "[EdgeBar]",
        "Meter=Image",
        "SolidColor=255,255,255,140",
        "X=0",
        f"Y={START_Y - 5}",
        "W=3",
        f"H={edge_bar_h}",
        "",
    ]

    for i, g in enumerate(games):
        gid = g["id"]
        tween_id = f"Tween{gid}"
        y_base = rest_y(i)
        label_y = y_base + (ICON_SIZE_HOVER // 2) - 6

        # Y is pushed down by the combined (fractional) growth of every
        # icon ABOVE this one - so partial/overlapping hovers blend
        # naturally instead of jumping.
        if i == 0:
            y_formula = str(y_base)
        else:
            push_terms = " + ".join(
                f'([Tween{games[k]["id"]}] / 100)' for k in range(i)
            )
            y_formula = f"({y_base} + #PushAmount# * ({push_terms}))"

        # size grows from IconSize to IconSizeHover based on this icon's
        # own tween value - smooth instead of an instant jump
        size_formula = (
            "(#IconSize# + ((#IconSizeHover# - #IconSize#) * "
            f"[{tween_id}] / 100))"
        )
        x_formula = "(#DockX# - #SlideDistance# + (#SlideDistance# * [FadeScript] / 255))"

        mouse_over = (
            '[!CommandMeasure FadeScript "Show()"]'
            f'[!CommandMeasure {tween_id} "Show()"]'
            f'[!SetOption {gid} "Greyscale" "0"]'
            '[!HideMeterGroup Labels]'
            f'[!ShowMeter Label{gid}]'
        )
        mouse_leave = (
            f'[!CommandMeasure {tween_id} "Hide()"]'
            f'[!SetOption {gid} "Greyscale" "1"]'
            f'[!HideMeter Label{gid}]'
        )
        # click-down: instant tactile dip, no delay - confirms the click
        # registered before anything even launches
        mouse_down = f'[!CommandMeasure {tween_id} "Punch()"]'
        mouse_up = f'["{g["shortcut"]}"]'

        lines += [
            f"; {'=' * 60}",
            f"; {g['name']}",
            f"; {'=' * 60}",
            f"[{gid}]",
            "Meter=Image",
            f"W={size_formula}",
            f"H={size_formula}",
            f"X={x_formula}",
            f"Y={y_formula}",
            "SolidColor=0,0,0,1",
            f"ImageName=assets/{g['image']}",
            "Greyscale=1",
            "ImageAlpha=[FadeScript]",
            "DynamicVariables=1",
            f"MouseOverAction={mouse_over}",
            f"MouseLeaveAction={mouse_leave}",
            f"LeftMouseDownAction={mouse_down}",
            f"LeftMouseUpAction={mouse_up}",
            "",
            f"[Label{gid}]",
            "Meter=String",
            "Group=Labels",
            "Hidden=1",
            "X=(#DockX# + #IconSizeHover# + #LabelGap#)",
            f"Y={label_y}",
            f"FontSize={FONT_SIZE}",
            f"FontFace={FONT_FACE}",
            "FontColor=#FontClr#",
            "AntiAlias=1",
            f"Text={g['name']}",
            "",
        ]

    return "\n".join(lines)


def main():
    games = load_manifest()
    if not games:
        sys.exit("ERROR: games.json is empty - add at least one entry.")

    print(f"Found {len(games)} game(s) in games.json:")
    for g in games:
        print(f"   - {g['name']}")
    print()

    check_assets(games)
    print()

    ini_text = build_ini(games)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(ini_text)

    print(f"✓ Wrote {OUTPUT_PATH}")
    print("  Now right-click the skin in Rainmeter -> Refresh Skin.")


if __name__ == "__main__":
    main()