[Rainmeter]
Author=Sylvane (Rasylver)
AppVersion=1.0
Update=1000

;===========================================
;  Battery Display
;===========================================

[Variables]
Drive=C
BarBack=255, 255, 255, 50
BarColor=255, 255, 255

FontName=Trebuchet MS
FontName2=Trebuchet MS
FontColor=255, 255, 255, 160
FontHeight=12
AntiAlias=1
;-------------------------

[MeasureHD]
Measure=FreeDiskSpace
Drive=#Drive#:

[MeasureHDInverse]
Measure=FreeDiskSpace
Drive=#Drive#:
InvertMeasure=1

;-----------------------------------------



[MeterHDDLabel]
Meter=STRING
Text="DISK"
X=10
Y=0
FontColor=#FontColor#
FontSize=#FontHeight#
FontFace=#FontName#
AntiAlias=1

[MeterBar]
MeasureName=MeasureHDInverse
Meter=BAR
X=10
Y=20
W=180
H=5
BarOrientation=HORIZONTAL
BarColor=#BarColor#

[BarLine]
Meter=IMAGE
X=12
Y=21
W=180
H=2
SolidColor=#BarBack#